### ISSUE TITLE
Huge Tile Missing

### ISSUE THREAD

**Issue by koufopoulosf** [bertt/geofabrik#1]
Hello,

I would like to say a huge thank you for your contribution🙏. I like your blog articles a lot and I would like to thank you very much for bringing up this tutorial.

I noticed that on Greece, a tile is missing:

![image](https://github.com/bertt/geofabrik/assets/66564413/dac1ced7-c8c2-4f8a-b2c3-72926f62eb91)

Do you know if that can be fixed?

Last, may I please ask you if you would recommend such solution for a production environment? Surely geofabrik has added as experimental those vector tiles, but they seem highly promising - like they're here to stay. Do you have any other suggestions maybe for serving nice basemaps to the web? Isn't this our best bet so far?

Thank you very much for your valuable time!

**Comment by bertt** [comment]
Hi thanks! From the image it looks like there are tiles in that area, but the content or rendering goes wrong somewhere? Maybe better ask Geofabrik about it?

**Comment by koufopoulosf** [comment]
I already asked VersaTiles since we are using their styles, however I will proceed and ask Geofabrik as well. Thank you!

**Comment by bertt** [comment]
Ok great let me know if you know more about it. About the second question: vector tiles is the way to go indeed, they look nice, render fast and deployment is easy (no need to maintain any servers just copy-paste deployment).

**Comment by koufopoulosf** [comment]
Thank you for your reply to my second question. Indeed, currently I am in between serving the vector tiles in a PMTiles format using Martin Tileserver, however the PMTiles file follows the OpenMapTiles scheme, so I would love a completely Open Source Solution such as of the project you mentioned in your blog/article ( https://github.com/versatiles-org ). Their styles look amazing as well. I wonder if we can serve those /{z}/{x}/{y}.pbf tiles instead of these on a PMTiles file. I will give it a try soon!

**Comment by bertt** [comment]
yeah PMTiles is also very interesting for huge tilesets, I did some experiments for example see https://bertt.wordpress.com/2023/01/06/creating-vector-pmtiles-with-tippecanoe/

**Comment by koufopoulosf** [comment]
Yeah. I want to serve PMTiles file for a country, but I do not know on your tutorial about shortbread, at the point where you mention that we need to change the tileserver to our own, how to make that PMTiles file to work with the shortbread style.json or how to convert the data the Geofabrik gives us to an MBTiles file (and then convert it to PMTiles).

In short, I am not sure if your point will work. I think Versatiles guys use their own format? https://github.com/versatiles-org/versatiles-converter
